"""empty message

Revision ID: 4714dd26a54e
Revises: b6901d58d77f
Create Date: 2020-11-15 14:03:20.097733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4714dd26a54e'
down_revision = 'b6901d58d77f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('h_class_r_class_id_fkey', 'h_class', type_='foreignkey')
    op.drop_constraint('h_class_l_class_id_fkey', 'h_class', type_='foreignkey')
    op.drop_column('h_class', 'l_class_id')
    op.drop_column('h_class', 'r_class_id')
    op.drop_constraint('l_class_d_class_Id_fkey', 'l_class', type_='foreignkey')
    op.drop_column('l_class', 'd_class_Id')
    op.add_column('matrix', sa.Column('d_class_id', sa.Integer(), nullable=True))
    op.add_column('matrix', sa.Column('l_class_id', sa.Integer(), nullable=True))
    op.add_column('matrix', sa.Column('r_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matrix', 'l_class', ['l_class_id'], ['id'])
    op.create_foreign_key(None, 'matrix', 'r_class', ['r_class_id'], ['id'])
    op.create_foreign_key(None, 'matrix', 'd_class', ['d_class_id'], ['id'])
    op.drop_constraint('r_class_d_class_Id_fkey', 'r_class', type_='foreignkey')
    op.drop_column('r_class', 'd_class_Id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('r_class', sa.Column('d_class_Id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('r_class_d_class_Id_fkey', 'r_class', 'd_class', ['d_class_Id'], ['id'])
    op.drop_constraint(None, 'matrix', type_='foreignkey')
    op.drop_constraint(None, 'matrix', type_='foreignkey')
    op.drop_constraint(None, 'matrix', type_='foreignkey')
    op.drop_column('matrix', 'r_class_id')
    op.drop_column('matrix', 'l_class_id')
    op.drop_column('matrix', 'd_class_id')
    op.add_column('l_class', sa.Column('d_class_Id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('l_class_d_class_Id_fkey', 'l_class', 'd_class', ['d_class_Id'], ['id'])
    op.add_column('h_class', sa.Column('r_class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('h_class', sa.Column('l_class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('h_class_l_class_id_fkey', 'h_class', 'l_class', ['l_class_id'], ['id'])
    op.create_foreign_key('h_class_r_class_id_fkey', 'h_class', 'r_class', ['r_class_id'], ['id'])
    # ### end Alembic commands ###
