"""empty message

Revision ID: 4ad0309ad97e
Revises: b154d5d3d48b
Create Date: 2020-11-11 03:12:30.831318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad0309ad97e'
down_revision = 'b154d5d3d48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r_classes_association')
    op.drop_table('l_classes_association')
    op.drop_table('h_classes_association')
    op.drop_table('d_classes_association')
    op.add_column('d_class', sa.Column('matrix_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'd_class', 'matrix', ['matrix_id'], ['id'])
    op.add_column('h_class', sa.Column('matrix_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'h_class', 'matrix', ['matrix_id'], ['id'])
    op.add_column('l_class', sa.Column('matrix_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'l_class', 'matrix', ['matrix_id'], ['id'])
    op.add_column('r_class', sa.Column('matrix_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'r_class', 'matrix', ['matrix_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'r_class', type_='foreignkey')
    op.drop_column('r_class', 'matrix_id')
    op.drop_constraint(None, 'l_class', type_='foreignkey')
    op.drop_column('l_class', 'matrix_id')
    op.drop_constraint(None, 'h_class', type_='foreignkey')
    op.drop_column('h_class', 'matrix_id')
    op.drop_constraint(None, 'd_class', type_='foreignkey')
    op.drop_column('d_class', 'matrix_id')
    op.create_table('d_classes_association',
    sa.Column('matrix_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('d_class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['d_class_id'], ['d_class.id'], name='d_classes_association_d_class_id_fkey'),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], name='d_classes_association_matrix_id_fkey')
    )
    op.create_table('h_classes_association',
    sa.Column('matrix_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('h_class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['h_class_id'], ['h_class.id'], name='h_classes_association_h_class_id_fkey'),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], name='h_classes_association_matrix_id_fkey')
    )
    op.create_table('l_classes_association',
    sa.Column('matrix_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('l_class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['l_class_id'], ['l_class.id'], name='l_classes_association_l_class_id_fkey'),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], name='l_classes_association_matrix_id_fkey')
    )
    op.create_table('r_classes_association',
    sa.Column('matrix_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('r_class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], name='r_classes_association_matrix_id_fkey'),
    sa.ForeignKeyConstraint(['r_class_id'], ['r_class.id'], name='r_classes_association_r_class_id_fkey')
    )
    # ### end Alembic commands ###
