"""empty message

Revision ID: 5d93d872b1f5
Revises: ba26f8ccb2ca
Create Date: 2020-11-11 03:00:56.313193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d93d872b1f5'
down_revision = 'ba26f8ccb2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hl_classes_association',
    sa.Column('l_class_id', sa.Integer(), nullable=True),
    sa.Column('h_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['h_class_id'], ['h_class.id'], ),
    sa.ForeignKeyConstraint(['l_class_id'], ['l_class.id'], )
    )
    op.create_table('hr_classes_association',
    sa.Column('r_class_id', sa.Integer(), nullable=True),
    sa.Column('h_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['h_class_id'], ['h_class.id'], ),
    sa.ForeignKeyConstraint(['r_class_id'], ['r_class.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hr_classes_association')
    op.drop_table('hl_classes_association')
    # ### end Alembic commands ###
