"""empty message

Revision ID: 87e9d6daa063
Revises: 99594e033f0a
Create Date: 2020-11-11 03:26:51.207962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e9d6daa063'
down_revision = '99594e033f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('h_class', sa.Column('l_class_id', sa.Integer(), nullable=True))
    op.add_column('h_class', sa.Column('r_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'h_class', 'l_class', ['l_class_id'], ['id'])
    op.create_foreign_key(None, 'h_class', 'r_class', ['r_class_id'], ['id'])
    op.drop_constraint('matrix_r_class_id_fkey', 'matrix', type_='foreignkey')
    op.drop_constraint('matrix_l_class_id_fkey', 'matrix', type_='foreignkey')
    op.drop_column('matrix', 'l_class_id')
    op.drop_column('matrix', 'r_class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrix', sa.Column('r_class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matrix', sa.Column('l_class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('matrix_l_class_id_fkey', 'matrix', 'l_class', ['l_class_id'], ['id'])
    op.create_foreign_key('matrix_r_class_id_fkey', 'matrix', 'r_class', ['r_class_id'], ['id'])
    op.drop_constraint(None, 'h_class', type_='foreignkey')
    op.drop_constraint(None, 'h_class', type_='foreignkey')
    op.drop_column('h_class', 'r_class_id')
    op.drop_column('h_class', 'l_class_id')
    # ### end Alembic commands ###
