"""empty message

Revision ID: 99594e033f0a
Revises: 4ad0309ad97e
Create Date: 2020-11-11 03:22:48.836916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99594e033f0a'
down_revision = '4ad0309ad97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('d_class_matrix_id_fkey', 'd_class', type_='foreignkey')
    op.drop_column('d_class', 'matrix_id')
    op.drop_constraint('h_class_matrix_id_fkey', 'h_class', type_='foreignkey')
    op.drop_column('h_class', 'matrix_id')
    op.drop_constraint('l_class_matrix_id_fkey', 'l_class', type_='foreignkey')
    op.drop_column('l_class', 'matrix_id')
    op.add_column('matrix', sa.Column('d_class_id', sa.Integer(), nullable=True))
    op.add_column('matrix', sa.Column('h_class_id', sa.Integer(), nullable=True))
    op.add_column('matrix', sa.Column('l_class_id', sa.Integer(), nullable=True))
    op.add_column('matrix', sa.Column('r_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matrix', 'd_class', ['d_class_id'], ['id'])
    op.create_foreign_key(None, 'matrix', 'l_class', ['l_class_id'], ['id'])
    op.create_foreign_key(None, 'matrix', 'h_class', ['h_class_id'], ['id'])
    op.create_foreign_key(None, 'matrix', 'r_class', ['r_class_id'], ['id'])
    op.drop_constraint('r_class_matrix_id_fkey', 'r_class', type_='foreignkey')
    op.drop_column('r_class', 'matrix_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('r_class', sa.Column('matrix_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('r_class_matrix_id_fkey', 'r_class', 'matrix', ['matrix_id'], ['id'])
    op.drop_constraint(None, 'matrix', type_='foreignkey')
    op.drop_constraint(None, 'matrix', type_='foreignkey')
    op.drop_constraint(None, 'matrix', type_='foreignkey')
    op.drop_constraint(None, 'matrix', type_='foreignkey')
    op.drop_column('matrix', 'r_class_id')
    op.drop_column('matrix', 'l_class_id')
    op.drop_column('matrix', 'h_class_id')
    op.drop_column('matrix', 'd_class_id')
    op.add_column('l_class', sa.Column('matrix_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('l_class_matrix_id_fkey', 'l_class', 'matrix', ['matrix_id'], ['id'])
    op.add_column('h_class', sa.Column('matrix_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('h_class_matrix_id_fkey', 'h_class', 'matrix', ['matrix_id'], ['id'])
    op.add_column('d_class', sa.Column('matrix_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('d_class_matrix_id_fkey', 'd_class', 'matrix', ['matrix_id'], ['id'])
    # ### end Alembic commands ###
