"""empty message

Revision ID: b6901d58d77f
Revises: 83b556042f0e
Create Date: 2020-11-12 01:08:26.967626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6901d58d77f'
down_revision = '83b556042f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('matrix_d_class_id_fkey', 'matrix', type_='foreignkey')
    op.drop_column('matrix', 'd_class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrix', sa.Column('d_class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('matrix_d_class_id_fkey', 'matrix', 'd_class', ['d_class_id'], ['id'])
    # ### end Alembic commands ###
