"""empty message

Revision ID: ba26f8ccb2ca
Revises: 5578cb0d6cb1
Create Date: 2020-11-11 01:44:39.529540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba26f8ccb2ca'
down_revision = '5578cb0d6cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('h_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('l_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('body', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('r_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('d_classes_association',
    sa.Column('matrix_id', sa.Integer(), nullable=True),
    sa.Column('d_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['d_class_id'], ['d_class.id'], ),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], )
    )
    op.create_table('h_classes_association',
    sa.Column('matrix_id', sa.Integer(), nullable=True),
    sa.Column('h_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['h_class_id'], ['h_class.id'], ),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], )
    )
    op.create_table('l_classes_association',
    sa.Column('matrix_id', sa.Integer(), nullable=True),
    sa.Column('l_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['l_class_id'], ['l_class.id'], ),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], )
    )
    op.create_table('r_classes_association',
    sa.Column('matrix_id', sa.Integer(), nullable=True),
    sa.Column('r_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrix.id'], ),
    sa.ForeignKeyConstraint(['r_class_id'], ['r_class.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r_classes_association')
    op.drop_table('l_classes_association')
    op.drop_table('h_classes_association')
    op.drop_table('d_classes_association')
    op.drop_table('r_class')
    op.drop_table('matrix')
    op.drop_table('l_class')
    op.drop_table('h_class')
    op.drop_table('d_class')
    # ### end Alembic commands ###
