"""empty message

Revision ID: f4c757b9ea3d
Revises: 
Create Date: 2021-02-09 01:18:11.126450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c757b9ea3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('h_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('l_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('r_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('body', sa.Integer(), nullable=True),
    sa.Column('h_class_id', sa.Integer(), nullable=True),
    sa.Column('l_class_id', sa.Integer(), nullable=True),
    sa.Column('r_class_id', sa.Integer(), nullable=True),
    sa.Column('d_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['d_class_id'], ['d_class.id'], ),
    sa.ForeignKeyConstraint(['h_class_id'], ['h_class.id'], ),
    sa.ForeignKeyConstraint(['l_class_id'], ['l_class.id'], ),
    sa.ForeignKeyConstraint(['r_class_id'], ['r_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matrix')
    op.drop_table('r_class')
    op.drop_table('l_class')
    op.drop_table('h_class')
    op.drop_table('d_class')
    # ### end Alembic commands ###
